### ISSUE TITLE
Strange behavior with nested negative lookaheads

### ISSUE THREAD

**Issue by gfredericks** [Engelberg/instaparse#87]
I was getting unexpected ambiguous parses on a complex grammar recently, and was able to minimize it to the following:

```
Regex = ElemBase *
ElemBase = CharNonRange | Range

(* these two are supposed to be mutually exclusive *)
Range = Char <'-'> Char
CharNonRange = Char ! ('-' Char)

Char = PlainChar | ControlChar
PlainChar = #"[-x]"
Dash = '-'
ControlChar = <'\\c'> (<'\\'> 'x' | (! '\\') 'x')
```

This is (I believe incorrectly) ambiguous when parsing `"x-\\cx"`, where we get the following two parses, and the first one is the one we want:

```
([:Regex
  [:ElemBase
   [:Range [:Char [:PlainChar "x"]] [:Char [:ControlChar "x"]]]]]
 [:Regex
  [:ElemBase [:CharNonRange [:Char [:PlainChar "x"]]]]
  [:ElemBase [:CharNonRange [:Char [:PlainChar "-"]]]]
  [:ElemBase [:CharNonRange [:Char [:ControlChar "x"]]]]])
```

For some reason the negative lookahead in `CharNonRange` is failing to eliminate the second case.

I can remove the ambiguity by expressing `ControlChar` without negative lookahead:

```
ControlChar = <'\\c'> ((<'\\'> 'x') | 'x')
```

but I don't think this should be necessary. Am I missing something about how negative lookahead works?

**Comment by Engelberg** [comment]
I've been working today on this bug, and I believe I have a patch.  You said you ran into it again in a different context.  Do you have a second test case I can use to test my patch?

**Comment by gfredericks** [comment]
oh man. it's been a while.

Looking back on the [grammar I ended up with](https://github.com/gfredericks/test.chuck/blob/1c9b9e59db84038911595dbe7888795a10c0ee8d/resources/com/gfredericks/test/chuck/regex.bnf) I can't find any references to this in the comments. I think I ended up simplifying the grammar at some point so I might have eliminated the bug-causing behavior.

Sorry.

**Comment by Engelberg** [comment]
Fixed in 1.4.0, so closing this issue.

**Comment by lvh** [comment]
FYI the relevant code in test.chuck is here: https://github.com/gfredericks/test.chuck/blob/master/src/com/gfredericks/test/chuck/regexes.clj#L371-L377

... I tried updating to instaparse 1.4.0 but it did not fix the issue. I'll try upgrading to the most recent version.
